<?php

function ps_planshop_menu_alter(&$items){
        if (empty($items['file/%file/download'])) { //replace with this line
                $items['file/%file/download'] = array(
                  'page callback' => 'commerce_file_download_page',
                  'page arguments' => array(1),
                  'access callback' => 'commerce_file_access',
                  'access arguments' => array('download', 1),
                  'type' => MENU_CALLBACK,
                );
        }
}

